### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by pcorpet**
I wasn't able to use dyanmoid-devise out of the box, and I figure out those changes.

[Review on Reviewable](https://reviewable.io/reviews/vinaycyadav/dynamoid-devise/1)

### CODE REVIEW

**Comment by pcorpet** [comment]
Thanks for the merge. Could you make a release please so that the Gemfile is usable?

**Comment by vinaycyadav** [comment]
Thanks Pascal for your fix. I am actually trying to test the gem, before publishing it to repo. but having hard time testing with sample app. Did you test with any sample app? if so, could you share that git with me please?

**Comment by pcorpet** [comment]
Hi Vinay, I did use it in one of my projects (I'm patching the Gem with the
diff I sent you).
Unfortunately I cannot share the git with you a it's not OpenSource at this
point.

Pascal

2016-04-05 16:00 GMT+02:00 Vinay C notifications@github.com:

**Comment by vinaycyadav** [comment]
No worries Pascal, I will go ahead & push new version of gem to repo in a day. Thanks & let me know if new gem serves the need.

Vinay C

**Pull request merged**
